### ISSUE TITLE
[BUG] usage of TYPO3 internal api - HasSecurityUpdate.php and HasUpdate.php

### ISSUE THREAD

**Issue by Teisi** [svewap/zabbix_client#27]
Both Classes don't work anymore cause of TYPO3 10.4.19 the TYPO3\CMS\Install\Service\CoreVersionService has changed a lot.

In my fork we use now the get.typo3 API for this:
https://github.com/Teisi/zabbix_client/blob/master/Classes/Operation/HasUpdate.php

**Comment by svewap** [comment]
This is a good time to revise the update checks. The ELTS cases must also be taken into account. In order not to reinvent the wheel, I will try to backport the current CoreVersionService.php file so that it can also be used under TYPO3 8-11.
In addition to the update and security update check, I will also introduce an outdated operation.

**Comment by svewap** [comment]
should be solved
